### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by barnett2010** [somethingcoolmustbehere/dumpPakKey#7]
C:\1\aeskeydunppakkey>dumpPakKey.exe Pal7-Win64-Shipping.exe
[!] Something went wrong, can't dump bytes to array.
[!] Something went wrong, can't generate key.
Traceback (most recent call last):
  File "dumpPakKey.py", line 137, in <module>
NameError: name 'b64' is not defined
[14752] Failed to execute script dumpPakKey

https://mega.nz/file/jdwARCRa#Vh3DtIMrYhPAr3p0g4vxbfC78C9w9UvieGOc9JgotHU

**Comment by ghGYR** [comment]
可以直接python 安装相关依赖包后 直接运行 没必要打包成exe，我也是在提取仙7资源，这个脚本很方便简直神器。

**Comment by ghGYR** [comment]
> C:\1\aeskeydunppakkey>dumpPakKey.exe Pal7-Win64-Shipping.exe
> [!] Something went wrong, can't dump bytes to array.
> [!] Something went wrong, can't generate key.
> Traceback (most recent call last):
> File "dumpPakKey.py", line 137, in
> NameError: name 'b64' is not defined
> [14752] Failed to execute script dumpPakKey
> 
> https://mega.nz/file/jdwARCRa#Vh3DtIMrYhPAr3p0g4vxbfC78C9w9UvieGOc9JgotHU

可以直接python 安装相关依赖包后 直接运行 没必要打包成exe，我也是在提取仙7资源，这个脚本很方便简直神器。
